/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisitRouteImport } from './routes/visit'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NewsRouteImport } from './routes/news'
import { Route as JourneysRouteImport } from './routes/journeys'
import { Route as ExhibitionsRouteImport } from './routes/exhibitions'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CurationRouteImport } from './routes/curation'
import { Route as CuratedRouteImport } from './routes/curated'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminShellRouteImport } from './routes/admin/_shell'
import { Route as AdminShellIndexRouteImport } from './routes/admin/_shell.index'
import { Route as AdminShellNewsRouteImport } from './routes/admin/_shell.news'
import { Route as AdminShellJourneysRouteImport } from './routes/admin/_shell.journeys'
import { Route as AdminShellExhibitionsRouteImport } from './routes/admin/_shell.exhibitions'
import { Route as AdminShellEventsRouteImport } from './routes/admin/_shell.events'
import { Route as AdminShellCuratedRouteImport } from './routes/admin/_shell.curated'
import { Route as AdminShellCollaborationsRouteImport } from './routes/admin/_shell.collaborations'
import { Route as AdminShellCategoriesRouteImport } from './routes/admin/_shell.categories'

const VisitRoute = VisitRouteImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneysRoute = JourneysRouteImport.update({
  id: '/journeys',
  path: '/journeys',
  getParentRoute: () => rootRouteImport,
} as any)
const ExhibitionsRoute = ExhibitionsRouteImport.update({
  id: '/exhibitions',
  path: '/exhibitions',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CurationRoute = CurationRouteImport.update({
  id: '/curation',
  path: '/curation',
  getParentRoute: () => rootRouteImport,
} as any)
const CuratedRoute = CuratedRouteImport.update({
  id: '/curated',
  path: '/curated',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShellRoute = AdminShellRouteImport.update({
  id: '/admin/_shell',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShellIndexRoute = AdminShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellNewsRoute = AdminShellNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellJourneysRoute = AdminShellJourneysRouteImport.update({
  id: '/journeys',
  path: '/journeys',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellExhibitionsRoute = AdminShellExhibitionsRouteImport.update({
  id: '/exhibitions',
  path: '/exhibitions',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellEventsRoute = AdminShellEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellCuratedRoute = AdminShellCuratedRouteImport.update({
  id: '/curated',
  path: '/curated',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellCollaborationsRoute =
  AdminShellCollaborationsRouteImport.update({
    id: '/collaborations',
    path: '/collaborations',
    getParentRoute: () => AdminShellRoute,
  } as any)
const AdminShellCategoriesRoute = AdminShellCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/curated': typeof CuratedRoute
  '/curation': typeof CurationRoute
  '/events': typeof EventsRoute
  '/exhibitions': typeof ExhibitionsRoute
  '/journeys': typeof JourneysRoute
  '/news': typeof NewsRoute
  '/privacy': typeof PrivacyRoute
  '/visit': typeof VisitRoute
  '/admin': typeof AdminShellRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/categories': typeof AdminShellCategoriesRoute
  '/admin/collaborations': typeof AdminShellCollaborationsRoute
  '/admin/curated': typeof AdminShellCuratedRoute
  '/admin/events': typeof AdminShellEventsRoute
  '/admin/exhibitions': typeof AdminShellExhibitionsRoute
  '/admin/journeys': typeof AdminShellJourneysRoute
  '/admin/news': typeof AdminShellNewsRoute
  '/admin/': typeof AdminShellIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/curated': typeof CuratedRoute
  '/curation': typeof CurationRoute
  '/events': typeof EventsRoute
  '/exhibitions': typeof ExhibitionsRoute
  '/journeys': typeof JourneysRoute
  '/news': typeof NewsRoute
  '/privacy': typeof PrivacyRoute
  '/visit': typeof VisitRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/categories': typeof AdminShellCategoriesRoute
  '/admin/collaborations': typeof AdminShellCollaborationsRoute
  '/admin/curated': typeof AdminShellCuratedRoute
  '/admin/events': typeof AdminShellEventsRoute
  '/admin/exhibitions': typeof AdminShellExhibitionsRoute
  '/admin/journeys': typeof AdminShellJourneysRoute
  '/admin/news': typeof AdminShellNewsRoute
  '/admin': typeof AdminShellIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/curated': typeof CuratedRoute
  '/curation': typeof CurationRoute
  '/events': typeof EventsRoute
  '/exhibitions': typeof ExhibitionsRoute
  '/journeys': typeof JourneysRoute
  '/news': typeof NewsRoute
  '/privacy': typeof PrivacyRoute
  '/visit': typeof VisitRoute
  '/admin/_shell': typeof AdminShellRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/_shell/categories': typeof AdminShellCategoriesRoute
  '/admin/_shell/collaborations': typeof AdminShellCollaborationsRoute
  '/admin/_shell/curated': typeof AdminShellCuratedRoute
  '/admin/_shell/events': typeof AdminShellEventsRoute
  '/admin/_shell/exhibitions': typeof AdminShellExhibitionsRoute
  '/admin/_shell/journeys': typeof AdminShellJourneysRoute
  '/admin/_shell/news': typeof AdminShellNewsRoute
  '/admin/_shell/': typeof AdminShellIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/curated'
    | '/curation'
    | '/events'
    | '/exhibitions'
    | '/journeys'
    | '/news'
    | '/privacy'
    | '/visit'
    | '/admin'
    | '/admin/login'
    | '/admin/categories'
    | '/admin/collaborations'
    | '/admin/curated'
    | '/admin/events'
    | '/admin/exhibitions'
    | '/admin/journeys'
    | '/admin/news'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/curated'
    | '/curation'
    | '/events'
    | '/exhibitions'
    | '/journeys'
    | '/news'
    | '/privacy'
    | '/visit'
    | '/admin/login'
    | '/admin/categories'
    | '/admin/collaborations'
    | '/admin/curated'
    | '/admin/events'
    | '/admin/exhibitions'
    | '/admin/journeys'
    | '/admin/news'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/curated'
    | '/curation'
    | '/events'
    | '/exhibitions'
    | '/journeys'
    | '/news'
    | '/privacy'
    | '/visit'
    | '/admin/_shell'
    | '/admin/login'
    | '/admin/_shell/categories'
    | '/admin/_shell/collaborations'
    | '/admin/_shell/curated'
    | '/admin/_shell/events'
    | '/admin/_shell/exhibitions'
    | '/admin/_shell/journeys'
    | '/admin/_shell/news'
    | '/admin/_shell/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CuratedRoute: typeof CuratedRoute
  CurationRoute: typeof CurationRoute
  EventsRoute: typeof EventsRoute
  ExhibitionsRoute: typeof ExhibitionsRoute
  JourneysRoute: typeof JourneysRoute
  NewsRoute: typeof NewsRoute
  PrivacyRoute: typeof PrivacyRoute
  VisitRoute: typeof VisitRoute
  AdminShellRoute: typeof AdminShellRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visit': {
      id: '/visit'
      path: '/visit'
      fullPath: '/visit'
      preLoaderRoute: typeof VisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journeys': {
      id: '/journeys'
      path: '/journeys'
      fullPath: '/journeys'
      preLoaderRoute: typeof JourneysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exhibitions': {
      id: '/exhibitions'
      path: '/exhibitions'
      fullPath: '/exhibitions'
      preLoaderRoute: typeof ExhibitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curation': {
      id: '/curation'
      path: '/curation'
      fullPath: '/curation'
      preLoaderRoute: typeof CurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curated': {
      id: '/curated'
      path: '/curated'
      fullPath: '/curated'
      preLoaderRoute: typeof CuratedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_shell': {
      id: '/admin/_shell'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_shell/': {
      id: '/admin/_shell/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminShellIndexRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/news': {
      id: '/admin/_shell/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminShellNewsRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/journeys': {
      id: '/admin/_shell/journeys'
      path: '/journeys'
      fullPath: '/admin/journeys'
      preLoaderRoute: typeof AdminShellJourneysRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/exhibitions': {
      id: '/admin/_shell/exhibitions'
      path: '/exhibitions'
      fullPath: '/admin/exhibitions'
      preLoaderRoute: typeof AdminShellExhibitionsRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/events': {
      id: '/admin/_shell/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminShellEventsRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/curated': {
      id: '/admin/_shell/curated'
      path: '/curated'
      fullPath: '/admin/curated'
      preLoaderRoute: typeof AdminShellCuratedRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/collaborations': {
      id: '/admin/_shell/collaborations'
      path: '/collaborations'
      fullPath: '/admin/collaborations'
      preLoaderRoute: typeof AdminShellCollaborationsRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/categories': {
      id: '/admin/_shell/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminShellCategoriesRouteImport
      parentRoute: typeof AdminShellRoute
    }
  }
}

interface AdminShellRouteChildren {
  AdminShellCategoriesRoute: typeof AdminShellCategoriesRoute
  AdminShellCollaborationsRoute: typeof AdminShellCollaborationsRoute
  AdminShellCuratedRoute: typeof AdminShellCuratedRoute
  AdminShellEventsRoute: typeof AdminShellEventsRoute
  AdminShellExhibitionsRoute: typeof AdminShellExhibitionsRoute
  AdminShellJourneysRoute: typeof AdminShellJourneysRoute
  AdminShellNewsRoute: typeof AdminShellNewsRoute
  AdminShellIndexRoute: typeof AdminShellIndexRoute
}

const AdminShellRouteChildren: AdminShellRouteChildren = {
  AdminShellCategoriesRoute: AdminShellCategoriesRoute,
  AdminShellCollaborationsRoute: AdminShellCollaborationsRoute,
  AdminShellCuratedRoute: AdminShellCuratedRoute,
  AdminShellEventsRoute: AdminShellEventsRoute,
  AdminShellExhibitionsRoute: AdminShellExhibitionsRoute,
  AdminShellJourneysRoute: AdminShellJourneysRoute,
  AdminShellNewsRoute: AdminShellNewsRoute,
  AdminShellIndexRoute: AdminShellIndexRoute,
}

const AdminShellRouteWithChildren = AdminShellRoute._addFileChildren(
  AdminShellRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CuratedRoute: CuratedRoute,
  CurationRoute: CurationRoute,
  EventsRoute: EventsRoute,
  ExhibitionsRoute: ExhibitionsRoute,
  JourneysRoute: JourneysRoute,
  NewsRoute: NewsRoute,
  PrivacyRoute: PrivacyRoute,
  VisitRoute: VisitRoute,
  AdminShellRoute: AdminShellRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
