/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisitRouteImport } from './routes/visit'
import { Route as PublicationsRouteImport } from './routes/publications'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NewsRouteImport } from './routes/news'
import { Route as JourneysRouteImport } from './routes/journeys'
import { Route as ExhibitionsRouteImport } from './routes/exhibitions'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CurationRouteImport } from './routes/curation'
import { Route as CuratedRouteImport } from './routes/curated'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout.index'
import { Route as VendorPendingRouteImport } from './routes/vendor/pending'
import { Route as VendorLoginRouteImport } from './routes/vendor/login'
import { Route as VendorShellRouteImport } from './routes/vendor/_shell'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'
import { Route as CheckoutCompleteRouteImport } from './routes/checkout.complete'
import { Route as AdminPendingRouteImport } from './routes/admin/pending'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminShellRouteImport } from './routes/admin/_shell'
import { Route as VendorShellIndexRouteImport } from './routes/vendor/_shell.index'
import { Route as AdminShellIndexRouteImport } from './routes/admin/_shell.index'
import { Route as VendorShellProductsRouteImport } from './routes/vendor/_shell.products'
import { Route as AdminShellStringsRouteImport } from './routes/admin/_shell.strings'
import { Route as AdminShellStockAlertsRouteImport } from './routes/admin/_shell.stock-alerts'
import { Route as AdminShellSettingsRouteImport } from './routes/admin/_shell.settings'
import { Route as AdminShellSalesRouteImport } from './routes/admin/_shell.sales'
import { Route as AdminShellRegistrationsRouteImport } from './routes/admin/_shell.registrations'
import { Route as AdminShellPublicationsRouteImport } from './routes/admin/_shell.publications'
import { Route as AdminShellProductsRouteImport } from './routes/admin/_shell.products'
import { Route as AdminShellPosRouteImport } from './routes/admin/_shell.pos'
import { Route as AdminShellPhonesRouteImport } from './routes/admin/_shell.phones'
import { Route as AdminShellPagesRouteImport } from './routes/admin/_shell.pages'
import { Route as AdminShellNewsRouteImport } from './routes/admin/_shell.news'
import { Route as AdminShellJourneysRouteImport } from './routes/admin/_shell.journeys'
import { Route as AdminShellInventoryVendorsRouteImport } from './routes/admin/_shell.inventory-vendors'
import { Route as AdminShellInventoryPurchasesRouteImport } from './routes/admin/_shell.inventory-purchases'
import { Route as AdminShellInventoryProductsRouteImport } from './routes/admin/_shell.inventory-products'
import { Route as AdminShellInventoryListingRouteImport } from './routes/admin/_shell.inventory-listing'
import { Route as AdminShellInventoryCountRouteImport } from './routes/admin/_shell.inventory-count'
import { Route as AdminShellInventoryCombosRouteImport } from './routes/admin/_shell.inventory-combos'
import { Route as AdminShellInventoryAdjustmentsRouteImport } from './routes/admin/_shell.inventory-adjustments'
import { Route as AdminShellExhibitionsRouteImport } from './routes/admin/_shell.exhibitions'
import { Route as AdminShellEventsRouteImport } from './routes/admin/_shell.events'
import { Route as AdminShellCuratedRouteImport } from './routes/admin/_shell.curated'
import { Route as AdminShellCollaborationsRouteImport } from './routes/admin/_shell.collaborations'
import { Route as AdminShellCategoriesRouteImport } from './routes/admin/_shell.categories'
import { Route as AdminShellPagesSlugRouteImport } from './routes/admin/_shell.pages.$slug'

const VisitRoute = VisitRouteImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsRoute = PublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneysRoute = JourneysRouteImport.update({
  id: '/journeys',
  path: '/journeys',
  getParentRoute: () => rootRouteImport,
} as any)
const ExhibitionsRoute = ExhibitionsRouteImport.update({
  id: '/exhibitions',
  path: '/exhibitions',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CurationRoute = CurationRouteImport.update({
  id: '/curation',
  path: '/curation',
  getParentRoute: () => rootRouteImport,
} as any)
const CuratedRoute = CuratedRouteImport.update({
  id: '/curated',
  path: '/curated',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorPendingRoute = VendorPendingRouteImport.update({
  id: '/vendor/pending',
  path: '/vendor/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorLoginRoute = VendorLoginRouteImport.update({
  id: '/vendor/login',
  path: '/vendor/login',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorShellRoute = VendorShellRouteImport.update({
  id: '/vendor/_shell',
  path: '/vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCompleteRoute = CheckoutCompleteRouteImport.update({
  id: '/checkout/complete',
  path: '/checkout/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPendingRoute = AdminPendingRouteImport.update({
  id: '/admin/pending',
  path: '/admin/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShellRoute = AdminShellRouteImport.update({
  id: '/admin/_shell',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorShellIndexRoute = VendorShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendorShellRoute,
} as any)
const AdminShellIndexRoute = AdminShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminShellRoute,
} as any)
const VendorShellProductsRoute = VendorShellProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => VendorShellRoute,
} as any)
const AdminShellStringsRoute = AdminShellStringsRouteImport.update({
  id: '/strings',
  path: '/strings',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellStockAlertsRoute = AdminShellStockAlertsRouteImport.update({
  id: '/stock-alerts',
  path: '/stock-alerts',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellSettingsRoute = AdminShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellSalesRoute = AdminShellSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellRegistrationsRoute = AdminShellRegistrationsRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellPublicationsRoute = AdminShellPublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellProductsRoute = AdminShellProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellPosRoute = AdminShellPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellPhonesRoute = AdminShellPhonesRouteImport.update({
  id: '/phones',
  path: '/phones',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellPagesRoute = AdminShellPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellNewsRoute = AdminShellNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellJourneysRoute = AdminShellJourneysRouteImport.update({
  id: '/journeys',
  path: '/journeys',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellInventoryVendorsRoute =
  AdminShellInventoryVendorsRouteImport.update({
    id: '/inventory-vendors',
    path: '/inventory-vendors',
    getParentRoute: () => AdminShellRoute,
  } as any)
const AdminShellInventoryPurchasesRoute =
  AdminShellInventoryPurchasesRouteImport.update({
    id: '/inventory-purchases',
    path: '/inventory-purchases',
    getParentRoute: () => AdminShellRoute,
  } as any)
const AdminShellInventoryProductsRoute =
  AdminShellInventoryProductsRouteImport.update({
    id: '/inventory-products',
    path: '/inventory-products',
    getParentRoute: () => AdminShellRoute,
  } as any)
const AdminShellInventoryListingRoute =
  AdminShellInventoryListingRouteImport.update({
    id: '/inventory-listing',
    path: '/inventory-listing',
    getParentRoute: () => AdminShellRoute,
  } as any)
const AdminShellInventoryCountRoute =
  AdminShellInventoryCountRouteImport.update({
    id: '/inventory-count',
    path: '/inventory-count',
    getParentRoute: () => AdminShellRoute,
  } as any)
const AdminShellInventoryCombosRoute =
  AdminShellInventoryCombosRouteImport.update({
    id: '/inventory-combos',
    path: '/inventory-combos',
    getParentRoute: () => AdminShellRoute,
  } as any)
const AdminShellInventoryAdjustmentsRoute =
  AdminShellInventoryAdjustmentsRouteImport.update({
    id: '/inventory-adjustments',
    path: '/inventory-adjustments',
    getParentRoute: () => AdminShellRoute,
  } as any)
const AdminShellExhibitionsRoute = AdminShellExhibitionsRouteImport.update({
  id: '/exhibitions',
  path: '/exhibitions',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellEventsRoute = AdminShellEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellCuratedRoute = AdminShellCuratedRouteImport.update({
  id: '/curated',
  path: '/curated',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellCollaborationsRoute =
  AdminShellCollaborationsRouteImport.update({
    id: '/collaborations',
    path: '/collaborations',
    getParentRoute: () => AdminShellRoute,
  } as any)
const AdminShellCategoriesRoute = AdminShellCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellPagesSlugRoute = AdminShellPagesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdminShellPagesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/curated': typeof CuratedRoute
  '/curation': typeof CurationRoute
  '/events': typeof EventsRoute
  '/exhibitions': typeof ExhibitionsRoute
  '/journeys': typeof JourneysRoute
  '/news': typeof NewsRoute
  '/privacy': typeof PrivacyRoute
  '/publications': typeof PublicationsRoute
  '/visit': typeof VisitRoute
  '/admin': typeof AdminShellRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/pending': typeof AdminPendingRoute
  '/checkout/complete': typeof CheckoutCompleteRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/vendor': typeof VendorShellRouteWithChildren
  '/vendor/login': typeof VendorLoginRoute
  '/vendor/pending': typeof VendorPendingRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/admin/categories': typeof AdminShellCategoriesRoute
  '/admin/collaborations': typeof AdminShellCollaborationsRoute
  '/admin/curated': typeof AdminShellCuratedRoute
  '/admin/events': typeof AdminShellEventsRoute
  '/admin/exhibitions': typeof AdminShellExhibitionsRoute
  '/admin/inventory-adjustments': typeof AdminShellInventoryAdjustmentsRoute
  '/admin/inventory-combos': typeof AdminShellInventoryCombosRoute
  '/admin/inventory-count': typeof AdminShellInventoryCountRoute
  '/admin/inventory-listing': typeof AdminShellInventoryListingRoute
  '/admin/inventory-products': typeof AdminShellInventoryProductsRoute
  '/admin/inventory-purchases': typeof AdminShellInventoryPurchasesRoute
  '/admin/inventory-vendors': typeof AdminShellInventoryVendorsRoute
  '/admin/journeys': typeof AdminShellJourneysRoute
  '/admin/news': typeof AdminShellNewsRoute
  '/admin/pages': typeof AdminShellPagesRouteWithChildren
  '/admin/phones': typeof AdminShellPhonesRoute
  '/admin/pos': typeof AdminShellPosRoute
  '/admin/products': typeof AdminShellProductsRoute
  '/admin/publications': typeof AdminShellPublicationsRoute
  '/admin/registrations': typeof AdminShellRegistrationsRoute
  '/admin/sales': typeof AdminShellSalesRoute
  '/admin/settings': typeof AdminShellSettingsRoute
  '/admin/stock-alerts': typeof AdminShellStockAlertsRoute
  '/admin/strings': typeof AdminShellStringsRoute
  '/vendor/products': typeof VendorShellProductsRoute
  '/admin/': typeof AdminShellIndexRoute
  '/vendor/': typeof VendorShellIndexRoute
  '/admin/pages/$slug': typeof AdminShellPagesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/curated': typeof CuratedRoute
  '/curation': typeof CurationRoute
  '/events': typeof EventsRoute
  '/exhibitions': typeof ExhibitionsRoute
  '/journeys': typeof JourneysRoute
  '/news': typeof NewsRoute
  '/privacy': typeof PrivacyRoute
  '/publications': typeof PublicationsRoute
  '/visit': typeof VisitRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pending': typeof AdminPendingRoute
  '/checkout/complete': typeof CheckoutCompleteRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/vendor/login': typeof VendorLoginRoute
  '/vendor/pending': typeof VendorPendingRoute
  '/checkout': typeof CheckoutIndexRoute
  '/shop': typeof ShopIndexRoute
  '/admin/categories': typeof AdminShellCategoriesRoute
  '/admin/collaborations': typeof AdminShellCollaborationsRoute
  '/admin/curated': typeof AdminShellCuratedRoute
  '/admin/events': typeof AdminShellEventsRoute
  '/admin/exhibitions': typeof AdminShellExhibitionsRoute
  '/admin/inventory-adjustments': typeof AdminShellInventoryAdjustmentsRoute
  '/admin/inventory-combos': typeof AdminShellInventoryCombosRoute
  '/admin/inventory-count': typeof AdminShellInventoryCountRoute
  '/admin/inventory-listing': typeof AdminShellInventoryListingRoute
  '/admin/inventory-products': typeof AdminShellInventoryProductsRoute
  '/admin/inventory-purchases': typeof AdminShellInventoryPurchasesRoute
  '/admin/inventory-vendors': typeof AdminShellInventoryVendorsRoute
  '/admin/journeys': typeof AdminShellJourneysRoute
  '/admin/news': typeof AdminShellNewsRoute
  '/admin/pages': typeof AdminShellPagesRouteWithChildren
  '/admin/phones': typeof AdminShellPhonesRoute
  '/admin/pos': typeof AdminShellPosRoute
  '/admin/products': typeof AdminShellProductsRoute
  '/admin/publications': typeof AdminShellPublicationsRoute
  '/admin/registrations': typeof AdminShellRegistrationsRoute
  '/admin/sales': typeof AdminShellSalesRoute
  '/admin/settings': typeof AdminShellSettingsRoute
  '/admin/stock-alerts': typeof AdminShellStockAlertsRoute
  '/admin/strings': typeof AdminShellStringsRoute
  '/vendor/products': typeof VendorShellProductsRoute
  '/admin': typeof AdminShellIndexRoute
  '/vendor': typeof VendorShellIndexRoute
  '/admin/pages/$slug': typeof AdminShellPagesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/curated': typeof CuratedRoute
  '/curation': typeof CurationRoute
  '/events': typeof EventsRoute
  '/exhibitions': typeof ExhibitionsRoute
  '/journeys': typeof JourneysRoute
  '/news': typeof NewsRoute
  '/privacy': typeof PrivacyRoute
  '/publications': typeof PublicationsRoute
  '/visit': typeof VisitRoute
  '/admin/_shell': typeof AdminShellRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/pending': typeof AdminPendingRoute
  '/checkout/complete': typeof CheckoutCompleteRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/vendor/_shell': typeof VendorShellRouteWithChildren
  '/vendor/login': typeof VendorLoginRoute
  '/vendor/pending': typeof VendorPendingRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/admin/_shell/categories': typeof AdminShellCategoriesRoute
  '/admin/_shell/collaborations': typeof AdminShellCollaborationsRoute
  '/admin/_shell/curated': typeof AdminShellCuratedRoute
  '/admin/_shell/events': typeof AdminShellEventsRoute
  '/admin/_shell/exhibitions': typeof AdminShellExhibitionsRoute
  '/admin/_shell/inventory-adjustments': typeof AdminShellInventoryAdjustmentsRoute
  '/admin/_shell/inventory-combos': typeof AdminShellInventoryCombosRoute
  '/admin/_shell/inventory-count': typeof AdminShellInventoryCountRoute
  '/admin/_shell/inventory-listing': typeof AdminShellInventoryListingRoute
  '/admin/_shell/inventory-products': typeof AdminShellInventoryProductsRoute
  '/admin/_shell/inventory-purchases': typeof AdminShellInventoryPurchasesRoute
  '/admin/_shell/inventory-vendors': typeof AdminShellInventoryVendorsRoute
  '/admin/_shell/journeys': typeof AdminShellJourneysRoute
  '/admin/_shell/news': typeof AdminShellNewsRoute
  '/admin/_shell/pages': typeof AdminShellPagesRouteWithChildren
  '/admin/_shell/phones': typeof AdminShellPhonesRoute
  '/admin/_shell/pos': typeof AdminShellPosRoute
  '/admin/_shell/products': typeof AdminShellProductsRoute
  '/admin/_shell/publications': typeof AdminShellPublicationsRoute
  '/admin/_shell/registrations': typeof AdminShellRegistrationsRoute
  '/admin/_shell/sales': typeof AdminShellSalesRoute
  '/admin/_shell/settings': typeof AdminShellSettingsRoute
  '/admin/_shell/stock-alerts': typeof AdminShellStockAlertsRoute
  '/admin/_shell/strings': typeof AdminShellStringsRoute
  '/vendor/_shell/products': typeof VendorShellProductsRoute
  '/admin/_shell/': typeof AdminShellIndexRoute
  '/vendor/_shell/': typeof VendorShellIndexRoute
  '/admin/_shell/pages/$slug': typeof AdminShellPagesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/contact'
    | '/curated'
    | '/curation'
    | '/events'
    | '/exhibitions'
    | '/journeys'
    | '/news'
    | '/privacy'
    | '/publications'
    | '/visit'
    | '/admin'
    | '/admin/login'
    | '/admin/pending'
    | '/checkout/complete'
    | '/shop/$slug'
    | '/vendor'
    | '/vendor/login'
    | '/vendor/pending'
    | '/checkout/'
    | '/shop/'
    | '/admin/categories'
    | '/admin/collaborations'
    | '/admin/curated'
    | '/admin/events'
    | '/admin/exhibitions'
    | '/admin/inventory-adjustments'
    | '/admin/inventory-combos'
    | '/admin/inventory-count'
    | '/admin/inventory-listing'
    | '/admin/inventory-products'
    | '/admin/inventory-purchases'
    | '/admin/inventory-vendors'
    | '/admin/journeys'
    | '/admin/news'
    | '/admin/pages'
    | '/admin/phones'
    | '/admin/pos'
    | '/admin/products'
    | '/admin/publications'
    | '/admin/registrations'
    | '/admin/sales'
    | '/admin/settings'
    | '/admin/stock-alerts'
    | '/admin/strings'
    | '/vendor/products'
    | '/admin/'
    | '/vendor/'
    | '/admin/pages/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/contact'
    | '/curated'
    | '/curation'
    | '/events'
    | '/exhibitions'
    | '/journeys'
    | '/news'
    | '/privacy'
    | '/publications'
    | '/visit'
    | '/admin/login'
    | '/admin/pending'
    | '/checkout/complete'
    | '/shop/$slug'
    | '/vendor/login'
    | '/vendor/pending'
    | '/checkout'
    | '/shop'
    | '/admin/categories'
    | '/admin/collaborations'
    | '/admin/curated'
    | '/admin/events'
    | '/admin/exhibitions'
    | '/admin/inventory-adjustments'
    | '/admin/inventory-combos'
    | '/admin/inventory-count'
    | '/admin/inventory-listing'
    | '/admin/inventory-products'
    | '/admin/inventory-purchases'
    | '/admin/inventory-vendors'
    | '/admin/journeys'
    | '/admin/news'
    | '/admin/pages'
    | '/admin/phones'
    | '/admin/pos'
    | '/admin/products'
    | '/admin/publications'
    | '/admin/registrations'
    | '/admin/sales'
    | '/admin/settings'
    | '/admin/stock-alerts'
    | '/admin/strings'
    | '/vendor/products'
    | '/admin'
    | '/vendor'
    | '/admin/pages/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/contact'
    | '/curated'
    | '/curation'
    | '/events'
    | '/exhibitions'
    | '/journeys'
    | '/news'
    | '/privacy'
    | '/publications'
    | '/visit'
    | '/admin/_shell'
    | '/admin/login'
    | '/admin/pending'
    | '/checkout/complete'
    | '/shop/$slug'
    | '/vendor/_shell'
    | '/vendor/login'
    | '/vendor/pending'
    | '/checkout/'
    | '/shop/'
    | '/admin/_shell/categories'
    | '/admin/_shell/collaborations'
    | '/admin/_shell/curated'
    | '/admin/_shell/events'
    | '/admin/_shell/exhibitions'
    | '/admin/_shell/inventory-adjustments'
    | '/admin/_shell/inventory-combos'
    | '/admin/_shell/inventory-count'
    | '/admin/_shell/inventory-listing'
    | '/admin/_shell/inventory-products'
    | '/admin/_shell/inventory-purchases'
    | '/admin/_shell/inventory-vendors'
    | '/admin/_shell/journeys'
    | '/admin/_shell/news'
    | '/admin/_shell/pages'
    | '/admin/_shell/phones'
    | '/admin/_shell/pos'
    | '/admin/_shell/products'
    | '/admin/_shell/publications'
    | '/admin/_shell/registrations'
    | '/admin/_shell/sales'
    | '/admin/_shell/settings'
    | '/admin/_shell/stock-alerts'
    | '/admin/_shell/strings'
    | '/vendor/_shell/products'
    | '/admin/_shell/'
    | '/vendor/_shell/'
    | '/admin/_shell/pages/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  CuratedRoute: typeof CuratedRoute
  CurationRoute: typeof CurationRoute
  EventsRoute: typeof EventsRoute
  ExhibitionsRoute: typeof ExhibitionsRoute
  JourneysRoute: typeof JourneysRoute
  NewsRoute: typeof NewsRoute
  PrivacyRoute: typeof PrivacyRoute
  PublicationsRoute: typeof PublicationsRoute
  VisitRoute: typeof VisitRoute
  AdminShellRoute: typeof AdminShellRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPendingRoute: typeof AdminPendingRoute
  CheckoutCompleteRoute: typeof CheckoutCompleteRoute
  ShopSlugRoute: typeof ShopSlugRoute
  VendorShellRoute: typeof VendorShellRouteWithChildren
  VendorLoginRoute: typeof VendorLoginRoute
  VendorPendingRoute: typeof VendorPendingRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visit': {
      id: '/visit'
      path: '/visit'
      fullPath: '/visit'
      preLoaderRoute: typeof VisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications': {
      id: '/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journeys': {
      id: '/journeys'
      path: '/journeys'
      fullPath: '/journeys'
      preLoaderRoute: typeof JourneysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exhibitions': {
      id: '/exhibitions'
      path: '/exhibitions'
      fullPath: '/exhibitions'
      preLoaderRoute: typeof ExhibitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curation': {
      id: '/curation'
      path: '/curation'
      fullPath: '/curation'
      preLoaderRoute: typeof CurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curated': {
      id: '/curated'
      path: '/curated'
      fullPath: '/curated'
      preLoaderRoute: typeof CuratedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/pending': {
      id: '/vendor/pending'
      path: '/vendor/pending'
      fullPath: '/vendor/pending'
      preLoaderRoute: typeof VendorPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/login': {
      id: '/vendor/login'
      path: '/vendor/login'
      fullPath: '/vendor/login'
      preLoaderRoute: typeof VendorLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/_shell': {
      id: '/vendor/_shell'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof VendorShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/complete': {
      id: '/checkout/complete'
      path: '/checkout/complete'
      fullPath: '/checkout/complete'
      preLoaderRoute: typeof CheckoutCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pending': {
      id: '/admin/pending'
      path: '/admin/pending'
      fullPath: '/admin/pending'
      preLoaderRoute: typeof AdminPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_shell': {
      id: '/admin/_shell'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/_shell/': {
      id: '/vendor/_shell/'
      path: '/'
      fullPath: '/vendor/'
      preLoaderRoute: typeof VendorShellIndexRouteImport
      parentRoute: typeof VendorShellRoute
    }
    '/admin/_shell/': {
      id: '/admin/_shell/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminShellIndexRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/vendor/_shell/products': {
      id: '/vendor/_shell/products'
      path: '/products'
      fullPath: '/vendor/products'
      preLoaderRoute: typeof VendorShellProductsRouteImport
      parentRoute: typeof VendorShellRoute
    }
    '/admin/_shell/strings': {
      id: '/admin/_shell/strings'
      path: '/strings'
      fullPath: '/admin/strings'
      preLoaderRoute: typeof AdminShellStringsRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/stock-alerts': {
      id: '/admin/_shell/stock-alerts'
      path: '/stock-alerts'
      fullPath: '/admin/stock-alerts'
      preLoaderRoute: typeof AdminShellStockAlertsRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/settings': {
      id: '/admin/_shell/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminShellSettingsRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/sales': {
      id: '/admin/_shell/sales'
      path: '/sales'
      fullPath: '/admin/sales'
      preLoaderRoute: typeof AdminShellSalesRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/registrations': {
      id: '/admin/_shell/registrations'
      path: '/registrations'
      fullPath: '/admin/registrations'
      preLoaderRoute: typeof AdminShellRegistrationsRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/publications': {
      id: '/admin/_shell/publications'
      path: '/publications'
      fullPath: '/admin/publications'
      preLoaderRoute: typeof AdminShellPublicationsRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/products': {
      id: '/admin/_shell/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminShellProductsRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/pos': {
      id: '/admin/_shell/pos'
      path: '/pos'
      fullPath: '/admin/pos'
      preLoaderRoute: typeof AdminShellPosRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/phones': {
      id: '/admin/_shell/phones'
      path: '/phones'
      fullPath: '/admin/phones'
      preLoaderRoute: typeof AdminShellPhonesRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/pages': {
      id: '/admin/_shell/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminShellPagesRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/news': {
      id: '/admin/_shell/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminShellNewsRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/journeys': {
      id: '/admin/_shell/journeys'
      path: '/journeys'
      fullPath: '/admin/journeys'
      preLoaderRoute: typeof AdminShellJourneysRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/inventory-vendors': {
      id: '/admin/_shell/inventory-vendors'
      path: '/inventory-vendors'
      fullPath: '/admin/inventory-vendors'
      preLoaderRoute: typeof AdminShellInventoryVendorsRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/inventory-purchases': {
      id: '/admin/_shell/inventory-purchases'
      path: '/inventory-purchases'
      fullPath: '/admin/inventory-purchases'
      preLoaderRoute: typeof AdminShellInventoryPurchasesRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/inventory-products': {
      id: '/admin/_shell/inventory-products'
      path: '/inventory-products'
      fullPath: '/admin/inventory-products'
      preLoaderRoute: typeof AdminShellInventoryProductsRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/inventory-listing': {
      id: '/admin/_shell/inventory-listing'
      path: '/inventory-listing'
      fullPath: '/admin/inventory-listing'
      preLoaderRoute: typeof AdminShellInventoryListingRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/inventory-count': {
      id: '/admin/_shell/inventory-count'
      path: '/inventory-count'
      fullPath: '/admin/inventory-count'
      preLoaderRoute: typeof AdminShellInventoryCountRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/inventory-combos': {
      id: '/admin/_shell/inventory-combos'
      path: '/inventory-combos'
      fullPath: '/admin/inventory-combos'
      preLoaderRoute: typeof AdminShellInventoryCombosRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/inventory-adjustments': {
      id: '/admin/_shell/inventory-adjustments'
      path: '/inventory-adjustments'
      fullPath: '/admin/inventory-adjustments'
      preLoaderRoute: typeof AdminShellInventoryAdjustmentsRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/exhibitions': {
      id: '/admin/_shell/exhibitions'
      path: '/exhibitions'
      fullPath: '/admin/exhibitions'
      preLoaderRoute: typeof AdminShellExhibitionsRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/events': {
      id: '/admin/_shell/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminShellEventsRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/curated': {
      id: '/admin/_shell/curated'
      path: '/curated'
      fullPath: '/admin/curated'
      preLoaderRoute: typeof AdminShellCuratedRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/collaborations': {
      id: '/admin/_shell/collaborations'
      path: '/collaborations'
      fullPath: '/admin/collaborations'
      preLoaderRoute: typeof AdminShellCollaborationsRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/categories': {
      id: '/admin/_shell/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminShellCategoriesRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/pages/$slug': {
      id: '/admin/_shell/pages/$slug'
      path: '/$slug'
      fullPath: '/admin/pages/$slug'
      preLoaderRoute: typeof AdminShellPagesSlugRouteImport
      parentRoute: typeof AdminShellPagesRoute
    }
  }
}

interface AdminShellPagesRouteChildren {
  AdminShellPagesSlugRoute: typeof AdminShellPagesSlugRoute
}

const AdminShellPagesRouteChildren: AdminShellPagesRouteChildren = {
  AdminShellPagesSlugRoute: AdminShellPagesSlugRoute,
}

const AdminShellPagesRouteWithChildren = AdminShellPagesRoute._addFileChildren(
  AdminShellPagesRouteChildren,
)

interface AdminShellRouteChildren {
  AdminShellCategoriesRoute: typeof AdminShellCategoriesRoute
  AdminShellCollaborationsRoute: typeof AdminShellCollaborationsRoute
  AdminShellCuratedRoute: typeof AdminShellCuratedRoute
  AdminShellEventsRoute: typeof AdminShellEventsRoute
  AdminShellExhibitionsRoute: typeof AdminShellExhibitionsRoute
  AdminShellInventoryAdjustmentsRoute: typeof AdminShellInventoryAdjustmentsRoute
  AdminShellInventoryCombosRoute: typeof AdminShellInventoryCombosRoute
  AdminShellInventoryCountRoute: typeof AdminShellInventoryCountRoute
  AdminShellInventoryListingRoute: typeof AdminShellInventoryListingRoute
  AdminShellInventoryProductsRoute: typeof AdminShellInventoryProductsRoute
  AdminShellInventoryPurchasesRoute: typeof AdminShellInventoryPurchasesRoute
  AdminShellInventoryVendorsRoute: typeof AdminShellInventoryVendorsRoute
  AdminShellJourneysRoute: typeof AdminShellJourneysRoute
  AdminShellNewsRoute: typeof AdminShellNewsRoute
  AdminShellPagesRoute: typeof AdminShellPagesRouteWithChildren
  AdminShellPhonesRoute: typeof AdminShellPhonesRoute
  AdminShellPosRoute: typeof AdminShellPosRoute
  AdminShellProductsRoute: typeof AdminShellProductsRoute
  AdminShellPublicationsRoute: typeof AdminShellPublicationsRoute
  AdminShellRegistrationsRoute: typeof AdminShellRegistrationsRoute
  AdminShellSalesRoute: typeof AdminShellSalesRoute
  AdminShellSettingsRoute: typeof AdminShellSettingsRoute
  AdminShellStockAlertsRoute: typeof AdminShellStockAlertsRoute
  AdminShellStringsRoute: typeof AdminShellStringsRoute
  AdminShellIndexRoute: typeof AdminShellIndexRoute
}

const AdminShellRouteChildren: AdminShellRouteChildren = {
  AdminShellCategoriesRoute: AdminShellCategoriesRoute,
  AdminShellCollaborationsRoute: AdminShellCollaborationsRoute,
  AdminShellCuratedRoute: AdminShellCuratedRoute,
  AdminShellEventsRoute: AdminShellEventsRoute,
  AdminShellExhibitionsRoute: AdminShellExhibitionsRoute,
  AdminShellInventoryAdjustmentsRoute: AdminShellInventoryAdjustmentsRoute,
  AdminShellInventoryCombosRoute: AdminShellInventoryCombosRoute,
  AdminShellInventoryCountRoute: AdminShellInventoryCountRoute,
  AdminShellInventoryListingRoute: AdminShellInventoryListingRoute,
  AdminShellInventoryProductsRoute: AdminShellInventoryProductsRoute,
  AdminShellInventoryPurchasesRoute: AdminShellInventoryPurchasesRoute,
  AdminShellInventoryVendorsRoute: AdminShellInventoryVendorsRoute,
  AdminShellJourneysRoute: AdminShellJourneysRoute,
  AdminShellNewsRoute: AdminShellNewsRoute,
  AdminShellPagesRoute: AdminShellPagesRouteWithChildren,
  AdminShellPhonesRoute: AdminShellPhonesRoute,
  AdminShellPosRoute: AdminShellPosRoute,
  AdminShellProductsRoute: AdminShellProductsRoute,
  AdminShellPublicationsRoute: AdminShellPublicationsRoute,
  AdminShellRegistrationsRoute: AdminShellRegistrationsRoute,
  AdminShellSalesRoute: AdminShellSalesRoute,
  AdminShellSettingsRoute: AdminShellSettingsRoute,
  AdminShellStockAlertsRoute: AdminShellStockAlertsRoute,
  AdminShellStringsRoute: AdminShellStringsRoute,
  AdminShellIndexRoute: AdminShellIndexRoute,
}

const AdminShellRouteWithChildren = AdminShellRoute._addFileChildren(
  AdminShellRouteChildren,
)

interface VendorShellRouteChildren {
  VendorShellProductsRoute: typeof VendorShellProductsRoute
  VendorShellIndexRoute: typeof VendorShellIndexRoute
}

const VendorShellRouteChildren: VendorShellRouteChildren = {
  VendorShellProductsRoute: VendorShellProductsRoute,
  VendorShellIndexRoute: VendorShellIndexRoute,
}

const VendorShellRouteWithChildren = VendorShellRoute._addFileChildren(
  VendorShellRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  CuratedRoute: CuratedRoute,
  CurationRoute: CurationRoute,
  EventsRoute: EventsRoute,
  ExhibitionsRoute: ExhibitionsRoute,
  JourneysRoute: JourneysRoute,
  NewsRoute: NewsRoute,
  PrivacyRoute: PrivacyRoute,
  PublicationsRoute: PublicationsRoute,
  VisitRoute: VisitRoute,
  AdminShellRoute: AdminShellRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminPendingRoute: AdminPendingRoute,
  CheckoutCompleteRoute: CheckoutCompleteRoute,
  ShopSlugRoute: ShopSlugRoute,
  VendorShellRoute: VendorShellRouteWithChildren,
  VendorLoginRoute: VendorLoginRoute,
  VendorPendingRoute: VendorPendingRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
